### ISSUE TITLE
[BUG] stale documentation for getting started

### ISSUE THREAD

**Issue by hkennyv** [ECSHackWeek/impedance.py#111]
**Describe the bug**
Documentation is stale for `getting-started.rst` and `getting-started.ipynb`, specifically where it still uses `impedance.circuits` and `impedance.plotting`. Added a list to the bottom of things I caught, feel free to add

**edit:** There are also some issues with using outdated circuit elements.

**To Reproduce**
See [`getting-started.rst`](https://github.com/ECSHackWeek/impedance.py/blob/master/docs/source/getting-started.rst)

**Expected behavior**
Use the new API:

```python
from impedance.models.circuits import CustomCircuit
```

and

```python
from impedance.visualization import plot_nyquist
```

**Additional context**
i've started a PR to fix this, need to update the notebook still

* old imports in `getting-started.rst`
* `getting-started.ipynb` is stale
* old circuit elements in circuit string in `getting-started.rst`

**Comment by BGerwe** [comment]
Good catch! I think all of the example notebooks were updated for the new module structure, but this was overlooked.

**Comment by mdmurbach** [comment]
Yeah, great catch. Thanks for already starting a PR as well! 😁
