### ISSUE TITLE
[BUG] Hard-Coded Columns for readBioLogic

### ISSUE THREAD

**Issue by nickbrady** [ECSHackWeek/impedance.py#116]
In "exampleDataBioLogic.mpt" it appears that frequency, Im(Z), and Re(Z) make up the 1st, 2nd and 3rd columns respectively, but I haven't found this to be universal. 

This is an issue because in preprocessing.py, function readBioLogic (as well as other funcs), the column numbers are hard coded as 1, 2, 3. 

I have an .mpt file (couldn't share here - but willing to share) where these columns, are in a different order, but the headers remain the same: "freq/Hz", "Re(Z)/Ohm", "-Im(Z)/Ohm".

If I use pandas to import from the mpt file it works very easily. I noticed you are not using pandas but perhaps there is a way to resolve this.

Proposed solution: (line 151 of preprocessing.py)
```python
# find the freq and Z columns
headers  = lines[number_header_lines-1].split('\t')
freq_col = [o for o, h in enumerate(headers) if h == 'freq/Hz'][0]
ReZ_col  = [o for o, h in enumerate(headers) if h == 'Re(Z)/Ohm'][0]
ImZ_col  = [o for o, h in enumerate(headers) if h == '-Im(Z)/Ohm'][0]

raw_data = lines[number_header_lines:]
f, Z = [], []
for line in raw_data:
    each = line.split('\t')
    f.append(float(each[freq_col]))

    # MPT data format saves the imaginary portion as -Im(Z) not Im(Z)
    Z.append(complex(float(each[ReZ_col]), -1*float(each[ImZ_col])))
```

This works on my data file as well as exampleDataBioLogic.mpt
But again, pandas does this already.

**Comment by mdmurbach** [comment]
👋 @nickbrady thanks for filing the issue and sharing your solution! In this case, I think parsing the columns is great. Would you be willing to submit a pull request (feel free to post here if you have any questions)?

One suggestion I might make is that I think this solution will throw an index error if a column doesn't exist (when it tries to get the [0] from an empty list), so it'd probably be good to add a step to check that it exists first and raise a more meaningful error, e.g.

```python
headers = lines[number_header_lines-1].split('\t')
freq_cols = [o for o, h in enumerate(headers) if h == 'freq/Hz']
ReZ_cols = [o for o, h in enumerate(headers) if h == 'Re(Z)/Ohm']
ImZ_cols = [o for o, h in enumerate(headers) if h == '-Im(Z)/Ohm']

for cols in [freq_cols, ReZ_cols, ImZ_cols]:
    assert len(cols) > 0, f'{cols} not found in header ({headers})'

freq_col = freq_cols[0]
ReZ_col = ReZ_cols[0]
ImZ_cols = ImZ_cols[0]
```
