### ISSUE TITLE
Plotting needs better defaults for big numbers

### ISSUE THREAD

**Issue by lktsui** [ECSHackWeek/impedance.py#12]
Not sure what the best way to address this is, but the default plotting commands don't work well on graphs which have impedances that are large. My typical values are on the order of kOhm to MOhms and the default unit mOhms resulting in gigantic numbers on the axis label.

![out_default](https://user-images.githubusercontent.com/22246069/46560788-3b559b00-c8b2-11e8-9e10-3bf17bb379a2.png)

**Comment by mdmurbach** [comment]
you're definitely right. it is currently hardwired to plot in mΩ. We should probably allow a user to pass a scale (i.e. 10e3 or 10e-6) and a unit (i.e. mΩ or MΩ).

**Comment by mdmurbach** [comment]
This was fixed by #14
