### ISSUE TITLE
Finding an error

### ISSUE THREAD

**Issue by ravuru66** [ECSHackWeek/impedance.py#120]
ModuleNotFoundError: No module named 'impedance'

could please help me in removing this error

**Comment by BGerwe** [comment]
Hi,

Can you include your import code and the full error message?

**Comment by BGerwe** [comment]
Hi @ravuru66, did you resolve the error? If so, I would like to close this issue in the next couple of days.

**Comment by ravuru66** [comment]
Thanks for the effort the error has been resolved

**Comment by BGerwe** [comment]
I'm glad to hear it! Then I will go ahead and close this issue.
