### ISSUE TITLE
Errors in Example Notebooks

### ISSUE THREAD

**Issue by EricaEgg** [ECSHackWeek/impedance.py#121]
Hi impedance.py team,

I found some errors while using some of your example notebooks. See below:

1) In the notebook, fitting_example.ipynb, part 4a, numpy is called without an import. Import line needs to be added in this block or earlier.
2) In the notebook plotting_example.ipynb, part 3a, I am getting an error. There could be a bug in the function circuit.plot. (error attached as photo)
<img width="529" alt="Screen Shot 2020-07-17 at 2 51 01 PM" src="https://user-images.githubusercontent.com/46461002/87833536-ef80a580-c83c-11ea-879a-f8abfb0b9568.png">

Let me know if I can clarify anything!

**Comment by mdmurbach** [comment]
Thanks for reporting this! I think this is an error with the javascript for vega (from altair) being loaded. Do you have an ad blocker running per chance?

**Comment by BGerwe** [comment]
For what it's worth, I just ran all the example notebooks after [Matt's fixes](https://github.com/ECSHackWeek/impedance.py/commit/2797d5fd68275855795cfb6e7d5610e77bea2314) in a fresh virtual environment and didn't get any errors.

**Comment by EricaEgg** [comment]
Thanks @mdmurbach and @BGerwe! I just re-ran it, and it is working perfectly.

**Comment by BGerwe** [comment]
Thanks for your work with the review @EricaEgg!
