### ISSUE TITLE
[Element]

### ISSUE THREAD

**Issue by dt-schwartz** [ECSHackWeek/impedance.py#140]
Please submit a reference and the equation for a proposed element! Attaching an example data set is also usually helpful :)

I have started building NLEIS equivalent circuits that use bits and pieces of your EIS elements. Your documentation has some elements written with frequency denoted by omega (rad/s, I presume) and others use f (Hz). Does every impedance.py element handle the 2*pi factor consistently (i.e., is every element based on Hz or rad/sec)?

**Comment by BGerwe** [comment]
Hi Dan,

The frequency list passed to the functions should be in Hz. Each element converts to radial frequency (rad/s) by `omega = 2*np.pi*np.array(f)`.
