### ISSUE TITLE
Add method for saving processed file

### ISSUE THREAD

**Issue by aokomorowski** [ECSHackWeek/impedance.py#141]
The library has a plenty of functions that allow processing data into single f, Z series. I think it would be nice to have an easy option to save these series into a file. I will create PR with solution shortly.

**Comment by mdmurbach** [comment]
Hi @aokomorowski. Sounds good, thanks. I think it might make sense to have a simple save data function in preprocessing.py. You could basically just use pandas.to_csv() and make it compatible with the read_csv() function already in there https://github.com/ECSHackWeek/impedance.py/blob/cf63337fa800ce768373163701bd175e74913f0e/impedance/preprocessing.py#L393-L399

**Comment by BGerwe** [comment]
Closing this because it was addressed by #167
