### ISSUE TITLE
Error when trying to add bounds to the fit(), shows 'x0' is infeasible.

### ISSUE THREAD

**Issue by yuchengluo** [ECSHackWeek/impedance.py#146]
frequencies, Z = preprocessing.ignoreBelowX(frequencies, Z)
from impedance.models.circuits import CustomCircuit

circuit = 'R0-p(R1,C1)-p(R2-Wo1,C2)'
initial_guess = [.01, .01, 100, .01, .05, 100, 1]
circuit = CustomCircuit(circuit, initial_guess=initial_guess)
bounds = ((0.5, 0.55, 13, 0.05, 0.6, 75, 0.02),(0.7, 10, 70, 0.3, 5, 167, 0.1))
circuit.fit(frequencies, Z, bounds=bounds)
Z_fit = circuit.predict(frequencies)

fig, ax = plt.subplots()
plot_nyquist(ax, Z, fmt='o')
plot_nyquist(ax, Z_fit, fmt='-')
plt.show()

error: ~\miniconda3\envs\impedance-analysis\lib\site-packages\scipy\optimize\_lsq\least_squares.py, line 795, raise ValueError("`x0` is infeasible.")

So how exactly should we set a boundary for each element? Please let me know if you have an answer. Thanks a lot!

**Comment by mdmurbach** [comment]
Guessing you figured this out, but in case anyone else runs into this issue, the above error means that at least one of the values in `initial_guess` is outside the limits passed in `bounds`
