### ISSUE TITLE
Fitting accuracy

### ISSUE THREAD

**Issue by yuchengluo** [ECSHackWeek/impedance.py#147]
Hi, thanks for the nice code first of all. I met some problems while using the code and need your help.
I am doing the fitting with several groups of data (data at different SOC level) from one single battery, so I give them the same initial-guess-value at the beginning. As you can see in the pictures, some of the fitting results are good, but others are not so precise, especially when it comes to high/low SOC level dataset. I have also added bounds for the data but I dont't think it works.
![12](https://user-images.githubusercontent.com/62569047/105371034-7c4d5700-5c04-11eb-89f4-90dc9eda53d2.png)
![20](https://user-images.githubusercontent.com/62569047/105371055-82433800-5c04-11eb-85c7-62366a0fce21.png)

circuit = 'R0-p(R1,C1)-p(R2-Wo1,C2)'
initial_guess = [.8, 1, 20, .1, 1, 100, .02]
bounds = ([0.7, 0.6, 20, 0.06, 0.6, 75, 0.01],[2, 6, 60, 0.4, 15, 290, 0.1])

Do you have any experience or ideas about how to fix the problem?

Thanks for your time and patience!

**Comment by mdmurbach** [comment]
If you know that the curves you are fitting vary smoothly over SoC, you can try passing the fit parameters from the previous SoC fit as the initial_guess values for the current SoC fit.

**Comment by yuchengluo** [comment]
> If you know that the curves you are fitting vary smoothly over SoC, you can try passing the fit parameters from the previous SoC fit as the initial_guess values for the current SoC fit.

Hi mdmurbach, thanks for your help. I tried to do the same way as you mentioned, use the previous fitting parameter to fit the inaccurate dataset, but the result was still not ideal, the curves look basically the same.
