### ISSUE TITLE
Travis CI shutting down

### ISSUE THREAD

**Issue by mdmurbach** [ECSHackWeek/impedance.py#149]
Travis-CI.org is shutting down and there appears to be [some issues](https://news.ycombinator.com/item?id=25338983) with open source projects getting credits with Travis-CI.com. 

We should figure out how to switch the testing over to GitHub Actions (or another CI platform) over the next few weeks 🙂

**Comment by ml-evs** [comment]
Hi there, I'm interested in using this package as part of a broader echem/materials data management suite - do you want a hand migrating to GitHub actions? I have a fair bit of experience with it.

**Comment by mdmurbach** [comment]
That's great. Sorry for the super long delay. Really appreciate the PR!

**Comment by ml-evs** [comment]
No problem, hope it's helpful!

I've just noticed that the CI documentation under CONTRIBUTING.md is now out of date, but should be fixable with `s/Travis/GitHub Actions/g`.
