### ISSUE TITLE
from impedance.models.circuits import CustomCircuit 

### ISSUE THREAD

**Issue by AIPM23** [ECSHackWeek/impedance.py#154]
**Describe the bug**
until yesterday was working fin now when I run: from impedance.models.circuits import CustomCircuit

Gives me the following error: No module named 'impedance.models'

Any suggestions?

**Comment by BGerwe** [comment]
Can you provide what version of impedance.py you're using? And a code snippet to replicate the behavior?

**Comment by AIPM23** [comment]
Thanks I found the error, apprently had to do with the update, after installing the update (!pip install --upgrade impedance) got solved. 

Thanks
