### ISSUE TITLE
TypeError when initial_guess is None

### ISSUE THREAD

**Issue by Rowin** [ECSHackWeek/impedance.py#16]
Hello,

The below snippet checks if `initial_guess` is not `None` but there is no action taken when it is actually `None`. Hence, when there is a further reference to the variable (e.g. `assert len(self.initial_guess)` on #L336) the script fails with a `TypeError`

https://github.com/ECSHackWeek/impedance.py/blob/3d62c111426e70392850d2053be866196ffc761b/impedance/circuits.py#L21

I see two ways to solve this:
-  raise an exception when `initial_guess` is `None`
- edit the doc to specify that `initial_guess` mandatory (I didn't see it, but if this information is already in the doc, sorry)

Thanks,

**Comment by mdmurbach** [comment]
Hi @Rowin,

Thanks for bringing this up! In terms of your suggestions for solving, I think basically a combo of the two makes sense, i.e. we should make sure to specify in the docs that passing an initial guess is currently mandatory and then check that initial_guess is passed with an assert statement.

I'd be glad to review a pull request if you'd like to open one for fixing the bug. Let me know if you have any other questions/suggestions. Happy to help however.

Thanks again and have a good weekend!
    ~ Matt
