### ISSUE TITLE
Fix certain parameters before attempting fit 

### ISSUE THREAD

**Issue by devangs3** [ECSHackWeek/impedance.py#169]
I am unable to fix one or multiple circuit parameters when it comes to trying a circuit model fit as Zview allows. Isthere a way the same can be done in this implementation? Here is a link for reference http://lacey.se/science/eis/fitting-with-real-data/

![image](https://user-images.githubusercontent.com/14045070/115652545-13ed3f00-a2f3-11eb-89ee-99801741aba0.png)

**Comment by svmchop** [comment]
Hi @devangs3 
There is an option to make circuit parameters constant. 
![image](https://user-images.githubusercontent.com/49499247/115858372-7c9bff00-a44c-11eb-8310-1cd37ba3c2f3.png)

**Comment by devangs3** [comment]
Could this be added to the documentation page? Or if you can provide a link to this syntax? @svmchop
