### ISSUE TITLE
add a `CITATION.cff` to the repository

### ISSUE THREAD

**Issue by hkennyv** [ECSHackWeek/impedance.py#173]
**Is your feature request related to a problem? Please describe.**
Stumbled on this [Github blog post](https://github.blog/2021-08-19-enhanced-support-citations-github/) on enhanced support for citations and immediately thought of this project. I feel like the hard work the maintainers put into this should be recognized and that having a citation would be a nice addition.

**Describe the solution you'd like**
This new feature is geared towards software citations, but I see in the `README` that the preferred method is to cite the article. You can include both a software and preferred article citation as well.

To implement this, we just need to add a `CITATION.cff` to the root of this repo and github will automatically add a citation under the repository description.

More info [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A, thank you for your awesome work!

---

I've started a PR on this that I'll link to this issue shortly..

**Comment by mdmurbach** [comment]
Thanks for thinking of this and extra thanks for following up with a PR!
