### ISSUE TITLE
Using bounds 

### ISSUE THREAD

**Issue by fatmaoza** [ECSHackWeek/impedance.py#192]
Hi,

currently I'm trying to figure out, how I can define bounds when fitting my model to a circuit. I tried e.g. the following:

circuit.fit(frequencies, Z, bounds=[(0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5),(1,1,1,1,1,1,1,1,1)])

However, I always get error messages. Is there a possibility to upload an example in the documentation?

**Comment by FTHuld** [comment]
Hi @fatmaoza.
bounds takes a tuple, not a list. Try replacing your [ ] with ( ), like this:

`circuit.fit(frequencies, Z, bounds=((0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5),(1,1,1,1,1,1,1,1,1)))`

**Comment by mdmurbach** [comment]
Thanks for the answer @FTHuld! Hopefully, that solves your issue @fatmaoza, but feel free to re-open or create a new issue if you still have any questions
