### ISSUE TITLE
exampleData.csv

### ISSUE THREAD

**Issue by dinisaurier** [ECSHackWeek/impedance.py#194]
Hi there,

I just started using impedance.py and I am also new to python, so please excuse my basic question(s).

I was wondering what kind of dataset I need for the tool to work. I am mainly asking because there are three columns in the exampleData.csv but I thought only the impedance Z and the frequency is needed. So I am a bit confused. Might it be current, voltage and frequency so that Z is calculated? In which order? The example does not have headings. I am so sorry I feel real dumb asking this.

Thanks a lot.

Kind regards
dinisaurier

**Comment by mdmurbach** [comment]
Hi @dinisaurier,

No worries, thanks for asking the question! It is a bit unclear from our documentation (I'll add a PR to update the docs to make it clearer), but the readCSV function expects the text file to have three columns in the form (frequency, Z_real, Z_imag). There are also [many other functions to read from different instruments standard formats ](https://impedancepy.readthedocs.io/en/latest/preprocessing.html)or you can read in the frequency and impedance data on your own using pandas, numpy, etc.
