### ISSUE TITLE
Reproducing Inductance Effect in Equivalent Circuit Modelling (Help Needed)

### ISSUE THREAD

**Issue by Muneebing** [ECSHackWeek/impedance.py#210]
Dear Community,
I have some EIS data for a certain cell type and it's Nyquist Plot looks pretty weird as the negative imaginary impedance is also quite high, and for this data I want to fit an equivalent circuit model, where I don't want to ignore the negative imaginary impedance points. So when i try to fit the model with the inductor included in the circuit model then the code some how does not fit the model quite well regardless of how many RC-elements I add (Please see the screenshot "Fit_with_L" where red is original data and blue is the fit) but when I fit the data without the inductor in the circuit model then it only fits to the positive side of the graph (please see screenshot "Fit_without_L").  
Could the community members please help me create the equivalent circuit model for this EIS data.
I am also attaching the CSV file of the EIS data, which is named as "Messdaten_EIS_MiEV"
Much thanks in advance!

![Fit_with_L](https://user-images.githubusercontent.com/105212042/180431426-493e59ab-871d-49d4-b54a-c0dde414c58b.png)
![Fit_without_L](https://user-images.githubusercontent.com/105212042/180431703-fa6ad585-72b5-4d2a-8ff1-27d40844cff4.png)

[Messdaten_EIS_MiEV.csv](https://github.com/ECSHackWeek/impedance.py/files/9167392/Messdaten_EIS_MiEV.csv)

**Comment by mdmurbach** [comment]
Going to go ahead and close this issue @Muneebing, but if you still have questions or issues, please feel free to reopen this issue or as a question in [the discussion section](https://github.com/ECSHackWeek/impedance.py/discussions/new?category=q-a)
