### ISSUE TITLE
[BUG] system interpretation of , and . 

### ISSUE THREAD

**Issue by Sergio-PY** [ECSHackWeek/impedance.py#214]
I had an issue with the preprocessing library wrongly interpreting the "," as a thousand separator rather than a decimal separator. This happened specifically with the readBioLogic function. I believe that is a regional/system interpretation of dots and commas. 

The computer running the code and exporting the Biologic datafiles has Spain as the region and Spanish language and keyboard configuration.

I was able to solve the code by adding:
    _from locale import atof, setlocale, LC_NUMERIC
    setlocale(LC_NUMERIC, '')_
At the beginning of the preprocessing library, and substituting all the "float" data type by "atof"

the readBioLogic function now reads as:

_def readBioLogic(filename):
    """ function for reading the .mpt file from Biologic
        EC-lab software

        Parameters
        ----------
        filename: string
            Filename of .mpt file to extract impedance data from

        Returns
        -------
        frequencies : np.ndarray
            Array of frequencies
        impedance : np.ndarray of complex numbers
            Array of complex impedances

        """

    with open(filename, 'r', encoding="latin-1") as input_file:
        lines = input_file.readlines()

    header_line = lines[1]

    # MPT data format has variable number of header lines
    number_header_lines = int(header_line.split(":")[1])

    # find the freq and Z columns
    headers = lines[number_header_lines-1].split('\t')

    freq_cols = [o for o, h in enumerate(headers) if h == 'freq/Hz']
    ReZ_cols = [o for o, h in enumerate(headers) if h == 'Re(Z)/Ohm']
    ImZ_cols = [o for o, h in enumerate(headers) if h == '-Im(Z)/Ohm']

    col_heads = ['freq/Hz', 'Re(Z)/Ohm', '-Im(Z)/Ohm']
    for cols, ch in zip([freq_cols, ReZ_cols, ImZ_cols], col_heads):
        assert len(cols) > 0, f'"{ch}" not found in column headers'

    freq_col = freq_cols[0]
    ReZ_col = ReZ_cols[0]
    ImZ_col = ImZ_cols[0]

    raw_data = lines[number_header_lines:]
    f, Z = [], []
    for line in raw_data:
        each = line.split('\t')
        f.append(atof(each[freq_col]))

        # MPT data format saves the imaginary portion as -Im(Z) not Im(Z)
        Z.append(complex(atof(each[ReZ_col]), -1*atof(each[ImZ_col])))

    return np.array(f), np.array(Z)_

I hope is helpful for someone and I think it might be interesting for the developers to include this modification in further builds.

Best wishes

Sergio

**Comment by mdmurbach** [comment]
Hi @Sergio-PY, I think this should have been fixed in #223 and released in [v1.4.2](https://github.com/ECSHackWeek/impedance.py/releases/tag/v1.4.2)

Please let us know if you still run into any issues
