### ISSUE TITLE
pip installation impedance 1.4.1 needs a update [BUG]

### ISSUE THREAD

**Issue by oslopanda** [ECSHackWeek/impedance.py#235]
In the pip installation v 1.4.1, 
/impedance/models/circuits)/circuits.py was not updated.
Since from numpy==1.20.0 the np.complex removed
for BaseCircuit.fit
if impedance.dtype != np.complex:
            raise TypeError('impedance array should have a complex ' +
                            f'dtype (currently {impedance.dtype})')

course an error:
module 'numpy' has no attribute 'complex'

i can see the issue has been fixed here but not in the pip release.

**Comment by mdmurbach** [comment]
Yep, thanks for pointing this out! Released [v1.4.2](https://pypi.org/project/impedance/1.4.2/)

@all-contributors please add @oslopanda for bug report
