### ISSUE TITLE
[BUG] It might not be a bug, but who knows

### ISSUE THREAD

**Issue by JuanCarlosZapata666** [ECSHackWeek/impedance.py#250]
I'm trying to run the example on "Getting started with impedance.py". But I keep getting the following error 
![Snip20230202_2](https://user-images.githubusercontent.com/124286184/216380221-f09688eb-ed9a-4e2e-b215-ce2627885c3d.png)

I'm not sure if it a bug.

Thanks!

**Comment by BGerwe** [comment]
It looks like you need to switch the order of the inputs. Try `plot_nyquist(Z, ax=ax, fmt='o')`

**Comment by mdmurbach** [comment]
Fixing this in #249

**Comment by JuanCarlosZapata666** [comment]
> It looks like you need to switch the order of the inputs. Try `plot_nyquist(Z, ax=ax, fmt='o')`

It worked, thank you very much!
