### ISSUE TITLE
Confusion with the word "initial_guess" used in CustomCircuit(circuit_string,initial_guess) 

### ISSUE THREAD

**Issue by Yugal0** [ECSHackWeek/impedance.py#278]
shouldn't it be called "parameters".
The name "initial_guess" suits well for the fitting, but when we in general want to create a custom circuit and just want to simulate it, then using the word "initial_guess" doesn't make sense.
for example the code below to simulate a RC parallel circuit
`freq=numpy.logspace(-2,3)`
`RC_parallel=CustomCircuit("p(R0,C0)",initial_guess=[1e2,1e-3])` 
`Z_RC_parallel=RC_parallel.predict(freq)`

rather the second line should be like
`RC_parallel=CustomCircuit("p(R0,C0)",parameters=[1e2,1e-3])` 

But for example if someone is doing fitting then, I think it completely makes sense to use "initial_guess"
`RC_parallel=CustomCircuit("p(R0,C0)",initial_guess=[1e2,1e-3])`
`print(RC_parallel.fit(freq,Z_data,weight_by_modulus=True))`

Maybe I will write in more detail later, but for now I have just mentioned in short. It may be a small point, but will make the project more beginner friendly.

**Comment by mdmurbach** [comment]
Hi @Yugal0, thanks for the comment. I see what you're saying, but I think if you understand that you're first instantiating a model and then predicting it, the use of initial_guess and .predit() work even if you don't fit. That said, I think it's likely to be pretty confusing to have multiple keywords that mean the same thing so I'd propose leaving as is.
