### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lunaxochi** [ECSHackWeek/impedance.py#28]
preprocessing.readGamry returns a tuple instead of an array. In the "Preprocessing" documentation, it says this should return an array of the frequencies and complex numbers, but when checking the type, it returns a tuple. Not a big issue, but the indexing is different, and can cause other problems later. 

My original code: 
import numpy as np
import impedance
import impedance.preprocessing

data = impedance.preprocessing.readGamry(os.path.join("filename.DTA"))
frequencies = data[:,0] <--error in this line because tuple is indexed by 1 number only (but I was indexing it as an array, with 2 numbers)

**Comment by mdmurbach** [comment]
Thanks for reporting the issue @lunaxochi!

It looks like all of the preprocessing functions return a tuple containing two arrays, so I think you should be able to just use `frequencies, Z = impedance.preprocessing.readGamry(os.path.join("filename.DTA"))`. Let me know if you run into any other issues.
