### ISSUE TITLE
Units of Capacitance? 

### ISSUE THREAD

**Issue by environmat** [ECSHackWeek/impedance.py#31]
First, thanks for the great work and providing such a cool tool! 

Second, with the potential on looking stupid, I did not figure out the units of the capacitance yet. Is it F, µF or what is it? 

Thanks, 
Matthias

**Comment by lucasCFO** [comment]
Yeah, it would be great to see the units when calling print(circuit) !

Thanks

**Comment by mdmurbach** [comment]
Hi @environmat and @lucasCFO, my apologies for missing this earlier! Capacitance is just in F and I agree that it would be great to print the units alongside the initial guesses/parameters. It looks like we could add a decorator to each circuit element with a unit field similar to how we store the number of parameters. Happy to review a pull request or other ideas!

**Comment by mdmurbach** [comment]
This was added in the v0.4 release!

You can update with `pip install --upgrade impedance` :smile:

**Comment by mdmurbach** [comment]
@all-contributors please add @environmat for bug
