### ISSUE TITLE
Fix parameter in fitting

### ISSUE THREAD

**Issue by lawrencerenna** [ECSHackWeek/impedance.py#34]
Hello,

Is there a way to fix a parameter (e.g. a resistor value) when fitting an equivalent circuit?

Thank you!

**Comment by mdmurbach** [comment]
This was added in v0.4!

You can update with `pip install --upgrade impedance`. Please let me know if you run into any issues with the new feature :smile:

**Comment by mdmurbach** [comment]
@all-contributors please add @lawrencerenna for ideas
