### ISSUE TITLE
[Documentation] Gerischer element documentation unclear

### ISSUE THREAD

**Issue by BGerwe** [ECSHackWeek/impedance.py#37]
The documentation for the Gerischer element is:
![image](https://user-images.githubusercontent.com/38819321/66364740-9bf13b00-e93f-11e9-820c-834709897b47.png)

But in circuit_elements.py the definition of this element is:
![image](https://user-images.githubusercontent.com/38819321/66364997-5da84b80-e940-11e9-80e5-2b8e321d9c93.png)
The documentation should be updated to reflect the code.

Alternatively, this element could be defined following Lu, Kreller, and Adler, 2009 (DOI: 10.1149/1.3079337) :
![image](https://user-images.githubusercontent.com/38819321/66365097-b11a9980-e940-11e9-96c0-90a74067bc78.png)
With equivalence between parameters as: 
![image](https://user-images.githubusercontent.com/38819321/66365604-7154b180-e942-11e9-8bfa-b9b1043dd724.png)

The benefit of this definition is R_G is interpretable as the impedance width (rather than an admittance as is the case with Y), and t_G is a characteristic time constant where the system begins transitioning from co-limited kinetics and diffusion to only diffusionally limited.

**Comment by mdmurbach** [comment]
Awesome, thanks for taking the time to write this up! :1st_place_medal: 

> The benefit of this definition is R_G is interpretable as the impedance width (rather than an admittance as is the case with Y), and t_G is a characteristic time constant where the system begins transitioning from co-limited kinetics and diffusion to only diffusionally limited.

I definitely would favor the more meaningful parameter interpretations, so I think it makes sense to redefine the element (isn't that the point of a version <1.0/beta anyways :wink:). Would you want to make these changes and submit a pull request? Happy to help answer any questions you might have along the way.

**Comment by BGerwe** [comment]
I think I've made the appropriate changes, but I'm not sure how to check how they'll appear rendered on the docs page. Also, this is my first time pushing to a repo owned by someone else, so I'm a little unclear if I need permissions and how exactly I should branch it.

**Comment by mdmurbach** [comment]
Awesome! :rocket: 

#### Pull Requests
To submit a PR you can fork the repository (this basically makes your own linked copy at BGerwe/impedance.py) using the button at the top right of the ECSHackWeek/impedance.py page

![image](https://user-images.githubusercontent.com/9369020/66501553-787ddb80-ea78-11e9-9195-7c0e0206827e.png)

Then clone your fork to your computer (`git clone https://github.com/BGerwe/impedance.py`), copy the changes over that you made, add, and commit (you probably want to check the changes locally -- see below -- first) to your own fork. Then, when you go back to your repo on GitHub you can click on the "New Pull Request" button to submit a pull request.

![image](https://user-images.githubusercontent.com/9369020/66501797-ee824280-ea78-11e9-906a-e7a0bafbe46c.png)

#### Checking the changes to docs locally
You can build the docs locally with make in the docs directory:
```bash
cd docs
make html
```
and then open `build/html/index.html` to see them!

Let me know if you run into any problems along the way!

**Comment by BGerwe** [comment]
This is tremendously helpful, thanks!
