### ISSUE TITLE
More data formats supported

### ISSUE THREAD

**Issue by lktsui** [ECSHackWeek/impedance.py#42]
**Is your feature request related to a problem? Please describe.**
As of 2019-10-17, we currently support Autolab, Parstat, and Gamry in the preprocessing input. We would like to support more formats to make it easier to get your data into the analyzer easily.

**Describe the solution you'd like**
We should support the importing of data formats from other instrument manufacturers. If you have an example of data format, please submit it here and we can work on adding support for your data format to the software.

**Describe alternatives you've considered**
It could be possible to get your data into a generic CSV, but that may require manual editing of the data into the format that our read generic file supports and that is an additional hurdle towards adoption of this software.

**Comment by BGerwe** [comment]
Do you have particular data formats in mind? I can help with including Versastat .par files and Solartron .z file types.

**Comment by lktsui** [comment]
Biologic's would be nice. I was told there was a text version of the data format.

I also have some data that came out of a PAR potentiostat controlled with PowerSuite that I would like to support.

**Comment by lktsui** [comment]
[Example for PowerSuite EIS datafile](https://github.com/ECSHackWeek/impedance.py/files/3745547/EIS530_NO2_100ppm_9.txt)

 It's almost an TSV except they have an extra space between each line for some unknown reason.

**Comment by BGerwe** [comment]
Interesting. In my limited experience with Biologic I found it necessary to export each data file to .txt with their EC-Lab software. Otherwise, the data is in a format unreadable by text editors like Notepad++ but, again, my experience with Biologic is limited.

I realize this isn't helpful for your situation, but I just wrote support for Solartron .z files, and VersaStudio .par files. 

[Example VersaStudio file](https://github.com/BGerwe/impedance.py/blob/master/Versastudio%20EIS%20Example.par)

It sounds like you're using a Princeton Applied Research potentiostat-- do you mind sharing what model? It seems like multiple control software can be used on the same potentiostat, so we may want to consider identifier data formats by the software rather than hardware.

**Comment by lktsui** [comment]
That was my understanding for Biologics as well. May be easiest to take whatever their EC-Lab exports in text format.

The data in my example comes from an old PAR 2273 on loan from another group running PowerSuite on Windows XP. Don't have access to the instrument any more unfortunately. 

I agree that grouping data reading ability by software makes more sense. Especially for a manufacturer as old as PAR, they have gone through a number of control software which use different data formats, not to mention 3rd party control software like Scribner's Z-plot. 

I would suggest something like: readVersaStudio, readPowerSuite, readZplot

**Comment by BGerwe** [comment]
Agreed. As for the PowerSuite data, is the example you provided unaltered? I was expecting some experiment settings to precede the data.

**Comment by lktsui** [comment]
Yes. I got it straight from the export to text option. 

PowerSuite has their own binary blob format for storing settings and results for a set of experiments and each experiment has to be individually exported to text in a format where experimental options aren't preserved.

**Comment by lktsui** [comment]
PowerSuite support added in https://github.com/lktsui/impedance.py/commit/cf476642b98f216aaf25d07647b89ad93c49cea1 over at my repository

**Comment by BGerwe** [comment]
Awesome! I'm finishing up the testing for Versastudio and Zplot. Will push to my repository by EoD.

**Comment by BGerwe** [comment]
Ok, everything has passed local checks. [BGerwe@ 40b87a9](https://github.com/BGerwe/impedance.py/commit/40b87a93f5541d29e808f3c9e7301d839ef9d635)

**Comment by mdmurbach** [comment]
These both look awesome! Great job of also including tests for each :rocket: 

I think you both have the ability to merge PRs, but I'd be happy to review them as well. Let me know if there's anything else I can help with!

**Comment by mdmurbach** [comment]
@all-contributors please add @lktsui   for code and tests
@all-contributors please add @BGerwe  for code and tests

**Comment by mdmurbach** [comment]
@all-contributors please add @lktsui for code and test
@all-contributors please add @BGerwe for code and test

**Comment by mdmurbach** [comment]
@all-contributors please add @lktsui for code and test

**Comment by mdmurbach** [comment]
@all-contributors please add @BGerwe for code and test

**Comment by mdmurbach** [comment]
@all-contributors please add @BGerwe for code and test

**Comment by mdmurbach** [comment]
Sorry for all the spam on this one... I thought adding this contributors bot would make things easier... (maybe it will now that it's setup haha).

**Comment by mdmurbach** [comment]
I also added a tip pointing to these new features in the getting started page in https://github.com/ECSHackWeek/impedance.py/commit/7babd5a74e9e7bfcf706c1720c4a2ed85bae98f1. Might eventually be worth adding some more documentation around how to use these functions, how to request a new addition, etc. on the preprocessing page as well.

For now 2 questions:
  - Should we leave this open for any more data types?
  - I'm thinking we can do a release of v0.5 with these updates or do you think there are more to add right now?

**Comment by BGerwe** [comment]
I think we should leave it open a little while longer. BioLogic is an easy target right now (even if it requires a tedious exporting step).

**Comment by mdmurbach** [comment]
:+1: Sounds good to me! Do you have access to a biologic instrument or are we still looking for someone with some data?

**Comment by lktsui** [comment]
I got a Biologic file from Samuel this week. Will add it to the repo when I get a chance

On Tue, Oct 22, 2019, 13:05 Matt Murbach <notifications@github.com<mailto:notifications@github.com>> wrote:

👍 Sounds good to me! Do you have access to a biologic instrument or are we still looking for someone with some data?

**Comment by BGerwe** [comment]
I added a BioLogic example data file [to my fork](https://github.com/BGerwe/impedance.py/blob/Bode/data/exampleDataBioLogic.mpt), if you're eager for it, but didn't get around to writing the support today.

**Comment by lktsui** [comment]
BioLogic data support added based off of the example that @BGerwe provided

https://github.com/lktsui/impedance.py/commit/cd00b6a8f11d0cb8126c9c4c42d03ace3d41c66e

Note: user runedevros is me. I can't figure out how to not get it to attribute to that handle I use for my personal stuff when I push on my home PC.

**Comment by BGerwe** [comment]
@mdmurbach I can't find the thread where you mentioned this, but go ahead an release as v0.5 if you want. I haven't had enough time to work on Bode plot functionality, and probably won't for a other couple of weeks.

**Comment by mdmurbach** [comment]
👍 awesome, sounds good @BGerwe 

@lktsui do you want to submit the PR for adding the biologic function?

**Comment by lktsui** [comment]
Is there a way to revert the changes that @BGerwe made to plotting.py? The pull request I sent is failing the tests since the biologic data file got pulled in Commit https://github.com/ECSHackWeek/impedance.py/pull/59/commits/827d47b8a34b937b2f6902b197c4f461c330c02a  along with some changes to plotting.py which were in progress.

**Comment by mdmurbach** [comment]
Released as a part of v0.5! aa37038

I’ll leave up to y’all if it makes sense to close this issue now or keep it open

**Comment by runedevros** [comment]
I would like to keep this open as a central place for people to submit requests for data format support.

**Comment by lktsui** [comment]
I would like to keep it open so that people can submit requests here for us to support their data formats.

**Comment by BGerwe** [comment]
In working to improve the test coverage of `preprocessing` I found we don't have any data for Autolab or Parstat. If anyone has access to those file types, please include them in the `data` directory. Thanks in advance!

**Comment by mdmurbach** [comment]
Maybe @linnetteteo or @vwhu have some example data? :smile:

**Comment by dt-schwartz** [comment]
There are raw data files for autolab impedance experiments in the supplemental files from @mdmurbach @vwhu paper. Search on the paper osf DOI 10.17605/OSF.IO/TDNWA

**Comment by dt-schwartz** [comment]
Definitely @vwhu and @linnetteteo have a sample file.

**Comment by mdmurbach** [comment]
The impedance files for the paper above are custom .csvs of time domain data that are written by autolab, but I think the files that make sense to add would be for the typical impedance output of the autolab instrument (i.e. you were to just do a typical EIS experiment).

**Comment by linnetteteo** [comment]
I do have data files from the parstat, although that uses the Versastudio software and I see that there is already an example versastudio .par file

**Comment by dt-schwartz** [comment]
Thx, Matt. Didn't really think about fact we are weirdos who do our own signal processing on the time domain data.

**Comment by BGerwe** [comment]
@linnetteteo Would you mind sending me the parstat file so I can check if the formatting is the same as versastat?

**Comment by lktsui** [comment]
Here's a CHInstruments 660E data file. I don't think we have a way of reading this format yet. 

The instrument saves it as a binary blob which we can't read by default but it is also possible to export it as text.

[data_chinstruments.txt](https://github.com/ECSHackWeek/impedance.py/files/4238102/data_chinstruments.txt)

**Comment by mdmurbach** [comment]
I propose we close this issue and direct new data format requests [use to the new "Data File Support" issue template](https://github.com/ECSHackWeek/impedance.py/issues/new?assignees=&labels=&template=data-file-support-request.md&title=%5BDATA%5D)!
