### ISSUE TITLE
Fitting method not passed to scipy.optimize.curve_fit in circuit.fit method[BUG]

### ISSUE THREAD

**Issue by BGerwe** [ECSHackWeek/impedance.py#61]
The circuit_fit function in fitting.py lists [accepts a method argument](https://github.com/ECSHackWeek/impedance.py/blob/aa370380580ed4e3165a8ed8b49b15e3c48ee392/impedance/fitting.py#L22-L23) but [never passes it to curve_fit](https://github.com/ECSHackWeek/impedance.py/blob/aa370380580ed4e3165a8ed8b49b15e3c48ee392/impedance/fitting.py#L96-L98)  function call. 

#### To show this behavior, I'll work off the example in the Getting Started document.

`import sys`
`sys.path.append('../../../')`

`from impedance.circuits import Randles, CustomCircuit`
`init = [.01, .005, .1, .001, 200]`
`randles = Randles(initial_guess=init)`

`import numpy as np`

`data = np.genfromtxt('exampleData.csv', delimiter=',')`

`frequencies = data[:,0]`
`Z = data[:,1] + 1j*data[:,2]`

`# keep only the impedance data in the first quandrant`
`frequencies = frequencies[np.imag(Z) < 0]`
`Z = Z[np.imag(Z) < 0]`

#### By specifying 'lm' method and providing bounds, we should get an error, but we don't:
`bounds = ([1e-3, 1e-3, 1e-3, 1e-3, 1e-3],[1e3, 1e3, 1e3, 1e3, 1e3])`
`randles.fit(frequencies, Z, bounds=bounds, method='lm')`
`print(randles)`

> Name: Randles
> Circuit string: R0-p(R1,C1)-W1
> Fit: True
> 
> Initial guesses:
>      R0 = 1.00e-02 [Ohm]
>      R1 = 5.00e-03 [Ohm]
>      C1 = 1.00e-01 [F]
>    W1_0 = 1.00e-03 [Ohm]
>    W1_1 = 2.00e+02 [sec]
> 
> Fit parameters:
>      R0 = 1.86e-02  (+/- 2.44e-04) [Ohm]
>      R1 = 1.15e-02  (+/- 3.10e-04) [Ohm]
>      C1 = 1.33e+00  (+/- 1.01e-01) [F]
>    W1_0 = 6.31e-02  (+/- 4.47e-03) [Ohm]
>    W1_1 = 2.22e+02  (+/- 3.56e+01) [sec]

#### Repeat using scipy directly to see expected behavior:
`from scipy.optimize import curve_fit`
`from impedance.fitting import wrapCircuit`

`popt, pcov = curve_fit(wrapCircuit(randles.circuit, randles.constants), frequencies,
                       np.hstack([Z.real, Z.imag]), p0=init,
                       bounds=bounds, maxfev=100000, ftol=1E-13, method='lm')`

#### Outputs:

> > ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-46-242d4448f929> in <module>
>       1 popt, pcov = curve_fit(wrapCircuit(randles.circuit, randles.constants), frequencies,
>       2                        np.hstack([Z.real, Z.imag]), p0=init,
> ----> 3                        bounds=bounds, maxfev=100000, ftol=1E-13, method='lm')
> 
> ~\Anaconda3\lib\site-packages\scipy\optimize\minpack.py in curve_fit(f, xdata, ydata, p0, sigma, absolute_sigma, check_finite, bounds, method, jac, **kwargs)
>     699 
>     700     if method == 'lm' and bounded_problem:
> --> 701         raise ValueError("Method 'lm' only works for unconstrained problems. "
>     702                          "Use 'trf' or 'dogbox' instead.")
>     703 
> 
> ValueError: Method 'lm' only works for unconstrained problems. Use 'trf' or 'dogbox' instead.

#### Whereas specifying 'trf' method replicates results from .fit method
`popt, pcov = curve_fit(wrapCircuit(randles.circuit, randles.constants), frequencies,
                       np.hstack([Z.real, Z.imag]), p0=init,
                       bounds=bounds, maxfev=100000, ftol=1E-13, method='trf')`
`popt`

> array([1.86146618e-02, 1.15477176e-02, 1.33331944e+00, 6.31473595e-02,
       2.22407301e+02])

>

**Comment by mdmurbach** [comment]
Released in [v0.5.1](https://pypi.org/project/impedance/0.5.1/)
