### ISSUE TITLE
fitting_tutorial.ipynb 404s

### ISSUE THREAD

**Issue by lktsui** [ECSHackWeek/impedance.py#8]
https://github.com/ECSHackWeek/impedance.py/blob/master/examples/fitting_tutorial.ipynb linked on the front page is a dead link.

**Comment by mdmurbach** [comment]
Fixed in commit [f42bdf](https://github.com/ECSHackWeek/impedance.py/commit/f42bdfe439a8e32a327db65475b9ed2d1e003de0). Thanks!
