### ISSUE TITLE
Enable multi-character circuit elements

### ISSUE THREAD

**Issue by nealde** [ECSHackWeek/impedance.py#81]
**Is your feature request related to a problem? Please describe.**
This feature request is two-fold - adding a new circuit element should be as easy as:
1. writing a new element function
2. updating a single list, which acts as the master list of permissible elements

and we should support multi-character elements, without integers in the names.

**Describe the solution you'd like**
A solution will look like this:

* A partial refactor of the evaluation framework which may or may not rely on different logic to parse the circuit string in order to support multi-character elements
* An updated inheritance structure such that only circuit_elements.py needs to be modified in order to add / remove a viable element.

**Comment by mdmurbach** [comment]
Added in #82! 🚀 🤖
